name: 'Actions Workflow'
on:
  # push:
  # pull_request:
  pull_request:
    types: [closed, assigned, opened, reopened]
  # schedule:
  #   - cron: '1 * * 1 0'
  repository_dispatch: #manual
    types: [custom_event_type]
  push:
    branches:
      - master
      - 'feature/*' # catches feature/a and feature/b but not feature/a/b
      - 'feature/**' # catches feature/a and feature/b and feature/a/b
      - '!feature/featC'
    # branches-ignore:
    #   - 'test/**'
    tags:
      - v1.*
    # tags-ignore:
    #   - v2.*
    paths:
      - '**.js'
      - '!filename.js'
    # paths-ignore:
    #   - 'docs/**'
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files Before Checkout
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v3 # checkout commit that triggered workflow
      - name: List Files After Checkout
        run: |
          pwd
          ls
      - name: env vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Simple JS Action
        id: greet
        # uses: actions/hello-world-javascript-action@master (not preferred as updated to branch might break)
        # uses: actions/hello-world-javascript-action@<commit-hash>
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
